wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699305514.171116
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 5
      13: darwin-x86_64
